kind: pipeline
type: ssh
name: deploy

server:
  host:
    from_secret: SSH_HOST
  user:
    from_secret: SSH_USER
  password:
    from_secret: SSH_PASSWORD

steps:
  - name: generate env
    environment:
      - VITE_API_URL:
          from_secret: VITE_API_URL
      - VITE_BASE_PATH:
          from_secret: VITE_BASE_PATH
      - VITE_CASDOOR_CLIENT_ID:
          from_secret: VITE_CASDOOR_CLIENT_ID
      - VITE_CASDOOR_URL:
          from_secret: VITE_CASDOOR_URL
    commands:
      - echo "VITE_API_URL=$VITE_API_URL" > .env
      - echo "VITE_BASE_PATH=$VITE_BASE_PATH" >> .env
      - echo "VITE_CASDOOR_CLIENT_ID=$VITE_CASDOOR_CLIENT_ID" >> .env
      - echo "VITE_CASDOOR_URL=$VITE_CASDOOR_URL" >> .env
      - echo "Generate .env DONE."
  - name: docker build
    commands:
      - ls -a
      - docker build -t codesmell-fe:latest .
  - name: docker up
    commands:
      - docker compose -f docker-compose.yaml up -d
  - name: remove dangling images
    commands:
      - docker images --filter "dangling=true" -q | xargs -r docker rmi
  - name: done
    commands:
      - echo "Deploy DONE. "
trigger:
  branch:
    include:
      - master
      - develop